ProjeNarmAfzar/Areas/Admin/Controllers/VideoCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using ProjeNarmAfzar.Application.Services.InterFaces.VideoCategory;
using ProjeNarmAfzar.Domain.ViewModels.VideoCategory;

namespace ProjeNarmAfzar.Areas.Admin.Controllers
{
    public class VideoCategoryController : AdminBaseController
    {
        #region Constroctor

        private readonly IVideoCategoryService _videoCategoryService;

        public VideoCategoryController(IVideoCategoryService videoCategoryService)
        {
            _videoCategoryService = videoCategoryService;
        }

        #endregion

        #region Video Category List

        [HttpGet]
        public async Task<IActionResult> VideoCategoryList()
        {
            var category = await _videoCategoryService.GetAllVideoCategories();
            return View(category);
        }

        #endregion

        #region Create  

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateVideoCategoryViewModel create)
        {
            if (ModelState.IsValid)
            {
                var result = await _videoCategoryService.CreateVideoCategory(create);
                switch (result)
                {
                    case CreateVideoCategoryResult.DuplicateCategory:
                        ModelState.AddModelError("TitleInUrl","این نام قبلا استفاده شده است");
                        break;
                    case CreateVideoCategoryResult.Success:
                        return RedirectToAction("VideoCategoryList");
                }
            }
            return View(create);
        }

        #endregion

        #region Edit

        public async Task<IActionResult> Edit(long id)
        {
            // get category for edit
            var category = await _videoCategoryService.GetVideoCategoryForEdit(id);

            // return not found if null
            if (category == null)
            {
                return NotFound();
            }
             
            // show data in form
            return View(category);
        }

        [HttpPost,ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditVideoCategoryViewModel edit)
        {
            if (ModelState.IsValid)
            {
                var result = await _videoCategoryService.EditVideoCategory(edit);
                switch (result)
                {
                    case EditVideoCategoryResult.DuplicateCategory:
                        ModelState.AddModelError("TitleInUrl","این نام قبلا استفاده شده است");
                        break;
                    case EditVideoCategoryResult.NotFound:
                        TempData["error message"] = "این دسته بندی یافت نشد ";
                        return RedirectToAction("VideoCategoryList");
                    case EditVideoCategoryResult.Success:
                        return RedirectToAction("VideoCategoryList");
                }
            }
            return View(edit);
        }

        #endregion
    }
}

ProjeNarmAfzar/Controllers/VideoController.cs
using Microsoft.AspNetCore.Mvc;
using ProjeNarmAfzar.Application.Services.InterFaces.Video;
using ProjeNarmAfzar.Domain.ViewModels.Video;

namespace ProjeNarmAfzar.Controllers
{
    public class VideoController : Controller
    {
        #region Constroctor

        private readonly IVideoService _videoService;

        public VideoController(IVideoService videoService)
        {
            _videoService = videoService;
        }

        #endregion

        #region Index
        [HttpGet("videos")]
        public async Task<IActionResult> Index(FilterVideoViewModel filter)
        {
            filter.VideoState = FilterVideoState.NotDeleted;
            var videos = await _videoService.FilterVideo(filter);
            return View(videos);
        }

        #endregion

        #region Video Detail
        [HttpGet("videos/{videoId}/{title}")]
        public async Task<IActionResult> VideoDetail(long videoId, string title)
        {
            var video = await _videoService.GetSingleVideo(videoId);
            if (video == null)
            {
                return NotFound();
            }
            return View(video);
        }

        #endregion
    }
}

ProjeNarmAfzar/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<!--
BeyondAdmin - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.3.6
Version: 1.6.0
Purchase: https://wrapbootstrap.com/theme/beyondadmin-adminapp-angularjs-mvc-WB06R48S4
-->

<html xmlns="http://www.w3.org/1999/xhtml">
<!-- Head -->
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>

    <meta name="description" content="Dashboard" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="shortcut icon" href="/admin/assets/img/favicon.png" type="image/x-icon">

    <!--Basic Styles-->
    <link href="/admin/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/admin/assets/css/bootstrap-rtl.min.css" rel="stylesheet" />
    <link href="/admin/assets/css/font-awesome.min.css" rel="stylesheet" />
    <link href="/admin/assets/css/weather-icons.min.css" rel="stylesheet" />

    <!--Fonts-->
    <style>
        @@font-face {
            font-family: 'WYekan';
            src: url('/admin/assets/fonts/BYekan.woff') format('woff');
            font-weight: normal;
            font-style: normal;
        }

        .ck-content {
            min-height: 200px;
        }
       
    </style>
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300" rel="stylesheet" type="text/css">

    <!--Beyond styles-->
    <link href="/admin/assets/css/beyond-rtl.min.css" rel="stylesheet" />
    <link href="/admin/assets/css/4095-rtl.min.css" rel="stylesheet" type="text/css" />
    <link href="/admin/assets/css/demo.min.css" rel="stylesheet" />
    <link href="/admin/assets/css/typicons.min.css" rel="stylesheet" />
    <link href="/admin/assets/css/animate.min.css" rel="stylesheet" />
    <link id="skin-link" href="" rel="stylesheet" type="text/css" />
    @RenderSection("styles", false)
</head>
<!-- /Head -->
<!-- Body -->
<body>
    <!-- Loading Container -->
    <div class="loading-container">
        <div class="loader"></div>
    </div>
    <!--  /Loading Container -->
    <!-- Navbar -->
    <div class="navbar">
        <div class="navbar-inner">
            <div class="navbar-container">
                <!-- Navbar Barnd -->
                <div class="navbar-header pull-right">
                    <a href="#" class="navbar-brand">
                    </a>
                </div>
                <!-- /Navbar Barnd -->
                <!-- Sidebar Collapse -->
                <div class="sidebar-collapse" id="sidebar-collapse">
                    <i class="collapse-icon fa fa-bars"></i>
                </div>
                <!-- /Sidebar Collapse -->
       
            </div>
        </div>
    </div>
    <!-- /Navbar -->
    <!-- Main Container -->
    <div class="main-container container-fluid">
        <!-- Page Container -->
        <div class="page-container">
            <!-- Page Sidebar -->
            <div class="page-sidebar" id="sidebar">
            <!-- Sidebar Menu -->
                <ul class="nav sidebar-menu">
                    <!--Dashboard-->
                    <li>
                        <a asp-area="Admin" asp-controller="VideoCategory" asp-action="VideoCategoryList">
                            <span class="menu-text"> لیست دسته بندی ویدیو ها </span>
                        </a>
                    </li>
                
                    <!--UI Elements-->
                    <li>
                        <a asp-area="Admin" asp-controller="Video" asp-action="VideoLists">
                            <span class="menu-text"> لیست ویدیو ها </span>
                        </a>
                    </li>
                </ul>
                <!-- /Sidebar Menu -->
            </div>
            <!-- /Page Sidebar -->
            <!-- Page Content -->
            <div class="page-content">
                <!-- Page Body -->
                <div class="page-body">
                    @RenderBody()
                </div>
                <!-- /Page Body -->
            </div>
            <!-- /Page Content -->
        </div>
        <!-- /Page Container -->
        <!-- Main Container -->

    </div>

    <!--Basic Scripts-->
    <script src="/admin/assets/js/jquery.min.js"></script>
    <script src="/admin/assets/js/bootstrap.min.js"></script>
    <script src="/admin/assets/js/slimscroll/jquery.slimscroll.min.js"></script>

    <!--Beyond Scripts-->
    <script src="/admin/assets/js/skins.min.js"></script>
    <script src="/admin/assets/js/beyond.min.js"></script>


    <!--Page Related Scripts-->
    <!--Sparkline Charts Needed Scripts-->
    <script src="/admin/assets/js/charts/sparkline/jquery.sparkline.js"></script>
    <script src="/admin/assets/js/charts/sparkline/sparkline-init.js"></script>

    <!--Easy Pie Charts Needed Scripts-->
    <script src="/admin/assets/js/charts/easypiechart/jquery.easypiechart.js"></script>
    <script src="/admin/assets/js/charts/easypiechart/easypiechart-init.js"></script>

    <!--Flot Charts Needed Scripts-->
    <script src="/admin/assets/js/charts/flot/jquery.flot.js"></script>
    <script src="/admin/assets/js/charts/flot/jquery.flot.resize.js"></script>
    <script src="/admin/assets/js/charts/flot/jquery.flot.pie.js"></script>
    <script src="/admin/assets/js/charts/flot/jquery.flot.tooltip.js"></script>
    <script src="/admin/assets/js/charts/flot/jquery.flot.orderBars.js"></script>
<script>

    //Sets The Hidden Chart Width
    $('#dashboard-bandwidth-chart')
        .data('width', $('.box-tabbs')
            .width() - 20);
    //Visitor Sources Pie Chart
    var data = [
        {
            data: [[1, 21]],
            color: '#fb6e52'
        },
        {
            data: [[1, 12]],
            color: '#e75b8d'
        },
        {
            data: [[1, 11]],
            color: '#a0d468'
        },
        {
            data: [[1, 10]],
            color: '#ffce55'
        },
        {
            data: [[1, 46]],
            color: '#5db2ff'
        }
    ];
    var placeholder = $("#dashboard-pie-chart-sources");
    placeholder.unbind();

    $.plot(placeholder, data, {
        series: {
            pie: {
                innerRadius: 0.45,
                show: true,
                stroke: {
                    width: 4
                }
            }
        }
    });

    //Visit Chart (Main Chart)
    var data2 = [{
            color: themesecondary,
            label: "بازدید مستقیم",
            data: [[3, 2], [4, 5], [5, 4], [6, 11], [7, 12], [8, 11], [9, 8], [10, 14], [11, 12], [12, 16], [13, 9],
                [14, 10], [15, 14], [16, 15], [17, 9]],

            lines: {
                show: true,
                fill: true,
                lineWidth: .1,
                fillColor: {
                    colors: [{
                        opacity: 0
                    }, {
                        opacity: 0.4
                    }]
                }
            },
            points: {
                show: false
            },
            shadowSize: 0
        },
        {
            color: themeprimary,
            label: "لینک از سایتها",
            data: [[3, 10], [4, 13], [5, 12], [6, 16], [7, 19], [8, 19], [9, 24], [10, 19], [11, 18], [12, 21], [13, 17],
                [14, 14], [15, 12], [16, 14], [17, 15]],
            bars: {
                order: 1,
                show: true,
                borderWidth: 0,
                barWidth: 0.4,
                lineWidth: .5,
                fillColor: {
                    colors: [{
                        opacity: 0.4
                    }, {
                        opacity: 1
                    }]
                }
            }
        },
        {
            color: themethirdcolor,
            label: "موتورهای جستجو",
            data: [[3, 14], [4, 11], [5, 10], [6, 9], [7, 5], [8, 8], [9, 5], [10, 6], [11, 4], [12, 7], [13, 4],
                [14, 3], [15, 4], [16, 6], [17, 4]],
            lines: {
                show: true,
                fill: false,
                fillColor: {
                    colors: [{
                        opacity: 0.3
                    }, {
                        opacity: 0
                    }]
                }
            },
            points: {
                show: true
            }
        }
    ];
    var options = {
        legend: {
            show: false
        },
        xaxis: {
            tickDecimals: 0,
            color: '#f3f3f3'
        },
        yaxis: {
            min: 0,
            color: '#f3f3f3',
            tickFormatter: function (val, axis) {
                return "";
            },
        },
        grid: {
            hoverable: true,
            clickable: false,
            borderWidth: 0,
            aboveData: false,
            color: '#fbfbfb'

        },
        tooltip: true,
        tooltipOpts: {
            defaultTheme: false,
            content: " <b>%x تیر ماه</b> , <b>%s</b> : <span>%y</span>",
        }
    };
    var placeholder = $("#dashboard-chart-visits");
    var plot = $.plot(placeholder, data2, options);

    //Real-Time Chart
    var realTimedata = [],
        realTimedata2 = [],
        totalPoints = 300;

    var getSeriesObj = function () {
        return [
            {
                data: getRandomData(),
                lines: {
                    show: true,
                    lineWidth: 1,
                    fill: true,
                    fillColor: {
                        colors: [
                            {
                                opacity: 0
                            }, {
                                opacity: 1
                            }
                        ]
                    },
                    steps: false
                },
                shadowSize: 0
            }, {
                data: getRandomData2(),
                lines: {
                    lineWidth: 0,
                    fill: true,
                    fillColor: {
                        colors: [
                            {
                                opacity: .5
                            }, {
                                opacity: 1
                            }
                        ]
                    },
                    steps: false
                },
                shadowSize: 0
            }
        ];
    };
    function getRandomData() {
        if (realTimedata.length > 0)
            realTimedata = realTimedata.slice(1);

        // Do a random walk

        while (realTimedata.length < totalPoints) {

            var prev = realTimedata.length > 0 ? realTimedata[realTimedata.length - 1] : 50,
                y = prev + Math.random() * 10 - 5;

            if (y < 0) {
                y = 0;
            } else if (y > 100) {
                y = 100;
            }
            realTimedata.push(y);
        }

        // Zip the generated y values with the x values

        var res = [];
        for (var i = 0; i < realTimedata.length; ++i) {
            res.push([i, realTimedata[i]]);
        }

        return res;
    }
    function getRandomData2() {
        if (realTimedata2.length > 0)
            realTimedata2 = realTimedata2.slice(1);

        // Do a random walk

        while (realTimedata2.length < totalPoints) {

            var prev = realTimedata2.length > 0 ? realTimedata[realTimedata2.length] : 50,
                y = prev - 25;

            if (y < 0) {
                y = 0;
            } else if (y > 100) {
                y = 100;
            }
            realTimedata2.push(y);
        }


        var res = [];
        for (var i = 0; i < realTimedata2.length; ++i) {
            res.push([i, realTimedata2[i]]);
        }

        return res;
    }
    // Set up the control widget
    var updateInterval = 500;
    var plot = $.plot("#dashboard-chart-realtime", getSeriesObj(), {
        yaxis: {
            color: '#f3f3f3',
            min: 0,
            max: 100,
            tickFormatter: function (val, axis) {
                return "";
            }
        },
        xaxis: {
            color: '#f3f3f3',
            min: 0,
            max: 100,
            tickFormatter: function (val, axis) {
                return "";
            }
        },
        grid: {
            hoverable: true,
            clickable: false,
            borderWidth: 0,
            aboveData: false
        },
        colors: ['#eee', themeprimary],
    });

    function update() {

        plot.setData(getSeriesObj());

        plot.draw();
        setTimeout(update, updateInterval);
    }
    update();


    //Initiates Easy Pie Chart instances in page
    InitiateEasyPieChart.init();

    //Initiates Sparkline Chart instances in page
    InitiateSparklineCharts.init();
</script>

<script src="/lib/modules/modules.js"></script>
@RenderSection("scripts", false)

</body>
<!--  /Body -->
</html>

ProjeNarmAfzar/Areas/Admin/Views/Shared/_NotFoundItemPartial.cshtml
<div class="alert alert-warning">
    <p> هیچ اطلاعاتی یافت نشد</p>
</div>